/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppForm {
    }
    interface AppRoot {
    }
    interface AppTable {
        "tasks": string[];
    }
    interface AppTitle {
        "title": string;
    }
    interface AppTodo {
    }
}
declare global {
    interface HTMLAppFormElement extends Components.AppForm, HTMLStencilElement {
    }
    var HTMLAppFormElement: {
        prototype: HTMLAppFormElement;
        new (): HTMLAppFormElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLAppTableElement extends Components.AppTable, HTMLStencilElement {
    }
    var HTMLAppTableElement: {
        prototype: HTMLAppTableElement;
        new (): HTMLAppTableElement;
    };
    interface HTMLAppTitleElement extends Components.AppTitle, HTMLStencilElement {
    }
    var HTMLAppTitleElement: {
        prototype: HTMLAppTitleElement;
        new (): HTMLAppTitleElement;
    };
    interface HTMLAppTodoElement extends Components.AppTodo, HTMLStencilElement {
    }
    var HTMLAppTodoElement: {
        prototype: HTMLAppTodoElement;
        new (): HTMLAppTodoElement;
    };
    interface HTMLElementTagNameMap {
        "app-form": HTMLAppFormElement;
        "app-root": HTMLAppRootElement;
        "app-table": HTMLAppTableElement;
        "app-title": HTMLAppTitleElement;
        "app-todo": HTMLAppTodoElement;
    }
}
declare namespace LocalJSX {
    interface AppForm {
        "onAddTask"?: (event: CustomEvent<any>) => void;
    }
    interface AppRoot {
    }
    interface AppTable {
        "tasks"?: string[];
    }
    interface AppTitle {
        "title"?: string;
    }
    interface AppTodo {
    }
    interface IntrinsicElements {
        "app-form": AppForm;
        "app-root": AppRoot;
        "app-table": AppTable;
        "app-title": AppTitle;
        "app-todo": AppTodo;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-form": LocalJSX.AppForm & JSXBase.HTMLAttributes<HTMLAppFormElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "app-table": LocalJSX.AppTable & JSXBase.HTMLAttributes<HTMLAppTableElement>;
            "app-title": LocalJSX.AppTitle & JSXBase.HTMLAttributes<HTMLAppTitleElement>;
            "app-todo": LocalJSX.AppTodo & JSXBase.HTMLAttributes<HTMLAppTodoElement>;
        }
    }
}
